apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: test-project
spec:
  # 3 Pods should exist at all times.
  replicas: 2
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        # Apply this label to pods and default
        # the Deployment label selector to this value
        app: test-app
    spec:
      containers:
      - name: test-app
        # Run this image
        image: mandeep2022/test-app:latest

---

kind: Service
apiVersion: v1
metadata:
  # Unique key of the Service instance
  name: test-app
spec:
  ports:
    # Accept traffic sent to port 3001
    - name: http
      port: 3000
      targetPort: 3000
  selector:
    # Loadbalance traffic across Pods matching
    # this label selector
    app: test-app
  # Create an HA proxy in the cloud provider
  # with an External IP address - *Only supported
  # by some cloud providers*
  type: LoadBalancer